version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports: # Correct indentation and key for 'ports'
      - "5434:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123 # Use POSTGRES_PASSWORD instead of POSTGRES_Password (case-sensitive)
      POSTGRES_DB: nest
    networks: # Corrected indentation for networks
      - freecodecamp

networks:
  freecodecamp:
